name: Terraform CI

on:
  pull_request:
    branches: ['main']

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          soft_fail: true

  terraform:
    runs-on: ubuntu-latest
    needs: checkov
    strategy:
      fail-fast: false
      matrix:
        directories:
          - terraform/hosts/dell
          - terraform/hp-sff/16gb
          - terraform/hp-sff/32gb

    defaults:
      run:
        working-directory: ${{ matrix.directories }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format and check
        run: terraform fmt -check

      - name: Init (no backend)
        run: terraform init -backend=false

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan
